"""Init Schema

Revision ID: 6f25baa10ae3
Revises: 
Create Date: 2026-02-27 16:38:29.617186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f25baa10ae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('budget_pref', sa.String(), nullable=True),
    sa.Column('mood_pref', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hotel_id'), 'users', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('area_name', sa.String(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('crowd_score', sa.Integer(), nullable=True),
    sa.Column('weather_score', sa.Integer(), nullable=True),
    sa.Column('price_score', sa.Integer(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('zone_color', sa.Enum('GREEN', 'YELLOW', 'RED', name='zonecolor'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_hotel_id'), 'zones', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('booking_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('temp_data_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_state_hotel_id'), 'booking_state', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_booking_state_id'), 'booking_state', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'BOT', name='roleenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_hotel_id'), 'hotels', ['hotel_id'], unique=True)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('budget_level', sa.String(), nullable=True),
    sa.Column('open_time', sa.String(), nullable=False),
    sa.Column('close_time', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_hotel_id'), 'restaurants', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_table('taxi_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('price_per_km', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_drivers_hotel_id'), 'taxi_drivers', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_taxi_drivers_id'), 'taxi_drivers', ['id'], unique=False)
    op.create_table('tourist_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('open_time', sa.String(), nullable=False),
    sa.Column('close_time', sa.String(), nullable=False),
    sa.Column('best_time', sa.String(), nullable=False),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tourist_places_hotel_id'), 'tourist_places', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_tourist_places_id'), 'tourist_places', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tourist_places_id'), table_name='tourist_places')
    op.drop_index(op.f('ix_tourist_places_hotel_id'), table_name='tourist_places')
    op.drop_table('tourist_places')
    op.drop_index(op.f('ix_taxi_drivers_id'), table_name='taxi_drivers')
    op.drop_index(op.f('ix_taxi_drivers_hotel_id'), table_name='taxi_drivers')
    op.drop_table('taxi_drivers')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_hotel_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_hotel_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_booking_state_id'), table_name='booking_state')
    op.drop_index(op.f('ix_booking_state_hotel_id'), table_name='booking_state')
    op.drop_table('booking_state')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_hotel_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hotel_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
