"""Add timestamps to BookingState

Revision ID: ac5f24cb892f
Revises: 6f25baa10ae3
Create Date: 2026-02-28 05:12:21.139408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5f24cb892f'
down_revision: Union[str, Sequence[str], None] = '6f25baa10ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('booking_state', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_state', 'updated_at')
    op.drop_column('booking_state', 'created_at')
    # ### end Alembic commands ###
